spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
      lifecycle-management: start-only
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - 127.0.0.1:26379
          - 127.0.0.1:26380
          - 127.0.0.1:26381

custom:
  cookie:
    secure: false
    same-site: Lax
