spring:
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
custom:
  jwt:
    accessToken:
      secret: SQ0LZKvPK5vjnZYUztpFTdIVWp6g9V3ShUwJJDhq+CxoWUtr/mmzfrdIUapuZyOBTTw0tLLt/Sr5SwS2ZZmeAw
      expirationSeconds: "#{60*10}"
    refreshToken:
      secret: GwV6FENutXhukvlvPMYU0OrYjDhCCeLRAj1mOJ9xA+qsy2HzB6fBIau8NK4Y853lzxi0JuGos6f4IyJ73bg5zw
      expirationSeconds: "#{60*60*24*7}"
